excerpt_separator: ""
pygments: false
highlighter: rouge
markdown: kramdown
url: http://tlaothong.github.io
title: Teerachai Laothong
tagline: A log of developer life
description: My sharing
paginate: 5
excerpt_separator: <!–break–>